# Rutas Base
spring.mvc.servlet.path=/api/v1

# Conexión MQTT
mqtt.broker.url=${MQTT_BROKER_URL:tcp://localhost:1883}

# Conexión al Simulador (Ex Stub)
stub.switch.url=${STUB_URL:http://localhost:8080/api/v1/switches/{idSwitch}/acciones}

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecowarm}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true