services:
  # Instanciación del broker MQTT.
  mosquitto-broker:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-network

  # Aprovisionamiento de PostgreSQL para guardar la configuración persistente.
  postgres-db:
    image: postgres:15-alpine
    container_name: iot_postgres_db
    environment:
      POSTGRES_USER: ecowarm_user
      POSTGRES_PASSWORD: ecowarmpass
      POSTGRES_DB: ecowarm
    ports:
      - "5432:5432"
    volumes:
      - ecowarm_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecowarm_user -d ecowarm"]
      interval: 10s
      timeout: 5s
      retries: 5

  engine:
    build:
      context: ..
      dockerfile: modules/engine/Dockerfile
    image: ecowarm-engine:latest
    container_name: ecowarm_engine
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      mosquitto-broker:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/ecowarm
      - DB_USER=ecowarm_user
      - DB_PASS=ecowarmpass
      - MQTT_BROKER_URL=tcp://mosquitto-broker:1883
      - STUB_URL=http://simulador:8081/api/v1/switches/{idSwitch}/acciones 
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  ecowarm_data: